Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -27,36 +27,36 @@ on:
 jobs:
 
 
-
-snyk:
-  permissions:
-    contents: read # for actions/checkout to fetch code
-    security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
-    actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
-  runs-on: ubuntu-latest
-  steps:
-    - uses: actions/checkout@v3
-
-    - name: Set up Snyk CLI to check for security issues
-      uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
-      env:
-        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-
-    - name: Snyk Code test
-      run: snyk code test --sarif > snyk-code.sarif || true
-
-    - name: Save Snyk Results
-      if: ${{ always() }}  # Always execute even if previous steps fail
-      run: |
-        mv snyk-code.sarif snyk-results-$(date +"%Y%m%d-%H%M%S").sarif
-        echo "✅ Snyk scan completed"
-
-    - name: Upload Snyk Results
-      if: ${{ always() }}  # Always execute even if previous steps fail
-      uses: actions/upload-artifact@v2
-      with:
-        name: snyk-results
-        path: snyk-results-*.sarif  # Uploads all SARIF files matching the pattern
+  
+  snyk:
+    permissions:
+      contents: read # for actions/checkout to fetch code
+      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+  
+      - name: Set up Snyk CLI to check for security issues
+        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+  
+      - name: Snyk Code test
+        run: snyk code test --sarif > snyk-code.sarif || true
+  
+      - name: Save Snyk Results
+        if: ${{ always() }}  # Always execute even if previous steps fail
+        run: |
+          mv snyk-code.sarif snyk-results-$(date +"%Y%m%d-%H%M%S").sarif
+          echo "✅ Snyk scan completed"
+  
+      - name: Upload Snyk Results
+        if: ${{ always() }}  # Always execute even if previous steps fail
+        uses: actions/upload-artifact@v2
+        with:
+          name: snyk-results
+          path: snyk-results-*.sarif  # Uploads all SARIF files matching the pattern
 
 
 
